apiVersion: v1
kind: Service
metadata:
  name:  contentmanagement-srv
spec:
  type: NodePort
  selector:
    app:  ContentManagement
  ports:
    - name:  contentmanagement
      protocol: TCP
      port: 4000
      targetPort: 4000
