apiVersion: v1
kind: Service
metadata:
  name: videostreaming-srv
spec:
  type: NodePort
  selector:
    app: videostreaming
  ports:
    - name: videostreaming
      protocol: TCP
      port: 4001
      targetPort: 4001
