name: deploy-videostreaming

on:
  push:
    branches:
      - master
    paths:
      - 'videostreaming/**'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - run: cd auth && focker build -t cyrinls/videostreaming .
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    - run: docker push cyrinls/videostreaming  
