name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd ContentManagement && npm install && npm run test:ci
    - uses: actions/checkout@v3
    - name: Pushing the docker image to DockerHub
      run: cd ContentManagement && npm install && npm run test:ci
    - uses: actions/checkout@v3
    - name: Deplyement of micoservice ContentManagement on kuberntes cluster
      run: cd ContentManagement && npm install && npm run test:ci
